//
//  DisclaimerView.swift
//  FoodToru
//
//  Created by Christine Chen on 11/7/25.
//

import SwiftUI

struct DisclaimerView: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.managedObjectContext) private var viewContext
    @Binding var hasSeenDisclaimer: Bool
    
    var body: some View {
        NavigationView {
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {
                    // Warning Icon
                    HStack {
                        Spacer()
                        Image(systemName: "exclamationmark.triangle.fill")
                            .font(.system(size: 60))
                            .foregroundColor(.orange)
                        Spacer()
                    }
                    .padding(.top, 20)
                    
                    // Title
                    Text("Important Disclaimer")
                        .font(.largeTitle)
                        .fontWeight(.bold)
                        .multilineTextAlignment(.center)
                        .frame(maxWidth: .infinity)
                    
                    // Disclaimer Content
                    VStack(alignment: .leading, spacing: 16) {
                        DisclaimerSection(
                            icon: "brain.head.profile",
                            title: "AI-Powered Analysis",
                            content: "Meal analysis in FoodToru is performed using artificial intelligence (AI) and large language models (LLMs). The results are generated by AI and may not always be accurate."
                        )
                        
                        DisclaimerSection(
                            icon: "stethoscope",
                            title: "Not Medical Advice",
                            content: "The nutritional information, calorie estimates, and health recommendations provided by this app are for informational purposes only and are not intended to replace professional medical or nutritional advice."
                        )
                        
                        DisclaimerSection(
                            icon: "person.badge.shield.checkmark",
                            title: "Consult Professionals",
                            content: "Always consult with a qualified healthcare provider, registered dietitian, or nutritionist before making significant changes to your diet or exercise routine, especially if you have medical conditions or dietary restrictions."
                        )
                        
                        DisclaimerSection(
                            icon: "exclamationmark.circle",
                            title: "Use at Your Own Risk",
                            content: "You acknowledge that you use this app at your own risk. FoodToru and its developers are not responsible for any decisions made based on the information provided by the app."
                        )
                    }
                    .padding(.horizontal)
                    
                    // Acknowledgment
                    VStack(alignment: .leading, spacing: 12) {
                        Text("By continuing, you acknowledge that:")
                            .font(.headline)
                            .fontWeight(.semibold)
                        
                        VStack(alignment: .leading, spacing: 8) {
                            AcknowledgmentItem(text: "You understand the limitations of AI-generated analysis")
                            AcknowledgmentItem(text: "You will not rely solely on this app for medical or nutritional decisions")
                            AcknowledgmentItem(text: "You will consult professionals for serious health concerns")
                            AcknowledgmentItem(text: "You use this app at your own risk")
                        }
                    }
                    .padding()
                    .background(Color.orange.opacity(0.1))
                    .cornerRadius(12)
                    .padding(.horizontal)
                }
                .padding(.vertical)
            }
            .navigationTitle("Disclaimer")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button("I Understand") {
                        // Save acknowledgment to Core Data
                        if UserPreferencesService.shared.acknowledgeDisclaimer(context: viewContext) {
                            hasSeenDisclaimer = true
                            dismiss()
                        } else {
                            // If Core Data save fails, fallback to UserDefaults
                            UserDefaults.standard.set(true, forKey: "hasSeenDisclaimer")
                            hasSeenDisclaimer = true
                            dismiss()
                        }
                    }
                    .fontWeight(.semibold)
                }
            }
        }
    }
}

// MARK: - Disclaimer Section
struct DisclaimerSection: View {
    let icon: String
    let title: String
    let content: String
    
    var body: some View {
        HStack(alignment: .top, spacing: 16) {
            Image(systemName: icon)
                .font(.title2)
                .foregroundColor(.orange)
                .frame(width: 30)
            
            VStack(alignment: .leading, spacing: 4) {
                Text(title)
                    .font(.headline)
                    .fontWeight(.semibold)
                
                Text(content)
                    .font(.body)
                    .foregroundColor(.secondary)
            }
        }
    }
}

// MARK: - Acknowledgment Item
struct AcknowledgmentItem: View {
    let text: String
    
    var body: some View {
        HStack(alignment: .top, spacing: 8) {
            Image(systemName: "checkmark.circle.fill")
                .foregroundColor(.orange)
                .font(.caption)
            
            Text(text)
                .font(.subheadline)
                .foregroundColor(.secondary)
        }
    }
}

#Preview {
    DisclaimerView(hasSeenDisclaimer: .constant(false))
        .environment(\.managedObjectContext, PersistenceController.preview.container.viewContext)
}

